Repository running-elephant/datart, pull requests merged in 2022-08, with the labels that each got.

#1815 fix: border radius can't be negative
  frontend/src/app/components/ChartGraph/BasicBarChart/config.ts
  frontend/src/app/components/ChartGraph/BasicRadarChart/config.ts
  frontend/src/app/components/ChartGraph/ClusterBarChart/config.ts
  frontend/src/app/components/ChartGraph/ClusterColumnChart/config.ts
  frontend/src/app/components/ChartGraph/PercentageStackBarChart/config.ts
  frontend/src/app/components/ChartGraph/PercentageStackColumnChart/config.ts
  frontend/src/app/components/ChartGraph/StackBarChart/config.ts
  frontend/src/app/components/ChartGraph/StackColumnChart/config.ts
  frontend/src/app/components/ChartGraph/WaterfallChart/config.ts
Labels: bug

#1818 fix: drag field issue when in aggregation mode
  frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDraggable/ChartDraggableTargetContainer.tsx
Labels: bug

#1825 修复view 中解析配置的schema，columns -》 name的问题
  server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
Labels: discussion

#1827 fix: 修复#1826 issue, ldap/oauth2认证自动注册用户时,秘钥加密两次导致鉴权失败("用户已修改密码"错误)
  server/src/main/java/datart/server/service/impl/ExternalRegisterServiceImpl.java
  server/src/main/java/datart/server/service/impl/UserServiceImpl.java
Labels: discussion

#1880 fix(ArrayConfig.tsx): 修复FILE和HTTP类型数据源，编辑表，并且修改配置后，会添加一条脏数据问题【#1878】
  frontend/src/app/pages/MainPage/pages/SourcePage/SourceDetailPage/ConfigComponent/ArrayConfig.tsx
Labels: status: validating, interaction: 👏Good Idea

#1814 fix: import resource problem, when dashboard contain relation
  server/src/main/java/datart/server/service/impl/DashboardServiceImpl.java
Labels: status: investigating

#1770 refactor: refactor parseDataProviderConfig method add @Override
  server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
Labels: status: investigating

#1910 fix: 修复资源迁移导入目录的时候没设置目录新的组织id问题
  server/src/main/java/datart/server/service/impl/FolderServiceImpl.java
Labels: status: investigating, type: bug

#1888 fix-#1885: 系统变量USERNAME和NAME取值一致
  frontend/package.json
  server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
Labels: status: planning, type: bug, priority: p2, interaction: 👏Good Idea
